spring:
  profiles:
    active: @profile.active@
  application:
    name: ${project.name}
  output:
    ansi:
      enabled: always
  mvc:
    static-path-pattern: /**

server:
  port: 8181

logging:
  level:
    - "*": info
  path: ./logs

member:
  service:
    version: 1.0.0

nacos:
  host: 192.168.6.106
  port: 8848

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
  provider:
    version: ${member.service.version}

disId:
  workerId: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"