spring:
  profiles:
    active: @profile.active@
  application:
    name: ${project.name}
  output:
    ansi:
      enabled: always
  mvc:
    static-path-pattern: /**

server:
  port: 8080

logging:
  path: ./logs
  level:
    root: INFO
    com.atinbo: DEBUG

member:
  service:
    version: 1.0.0
nacos:
  host: 192.168.6.106
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}
  consumer:
    version: ${member.service.version}
    check: false

disId:
  workerId: 1

dislock:
  pattern: single
  single-server:
    address: 192.168.6.103
    port: 6379
    password: 123456